version: '3.4'

services:
  aprendo-en-casa-offline-contenido:
    #image: aprendo-en-casa-offline-contenido.api
    image: "registry.minedu.gob.pe/ac1.0/aprendo-en-casa-offline-contenido.api:latest"
    #build:
    #  context: .
    #  dockerfile: Minedu.AprendoEnCasaOffLine.Contenido.Api/Dockerfile
    hostname: aprendo-en-casa-offline-contenido.api
    container_name: aprendo-en-casa-offline-contenido.api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_MONGODB: "mongodb://root:root@192.168.100.32:27017/contenidoDB?authSource=admin"
      ASPNETCORE_CORS: "*"
      HORA_DESCARGA_INICIO: "02:00:00"
      HORA_DESCARGA_INTERVALO: "00:30:00"
      SERVIDOR_INTERVALO: "500"
      RUTA_ARCHIVOS: "/app/archivos"
      RUTA_ACK: "/app/ack"
      RUTA_TRAZABILIDAD: "/app/trazabilidad"
      RUTA_CONTINUIDAD: "/app/continuidad"
      #LOCAL TOKEN
      TOKEN_SECRET: "THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN SECRET, IT CAN BE ANY STRING"
      TOKEN_USER: "DOWNLOADOFFLINE_DEV"
      TOKEN_PASSWORD: "rYWXlDIqFSsjrpFEehaqYFkcofOsdFLdhsZIsViF3a6WxHZq0CFDdg=="
      TOKEN_CLIENT_ID: "download-offline_dev"
      TOKEN_EXPIRES_DAYS: "7"
    networks:
    - ms
    ports:
    - 1903:80
    volumes:
    - ../_certificates:/https
    - ../_log:/app/Log
    - ../_data/archivos:/app/archivos
    - ../_data/ack:/app/ack
    - ../_data/trazabilidad:/app/trazabilidad
    - ../_data/continuidad:/app/continuidad

    restart: on-failure
networks:
    ms:
      external: true
