version: '3.4'

services:
  aprendo-en-casa-offline-contenido:
    image: aprendo-en-casa-offline-contenido.api
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: aprendo-en-casa-offline-contenido.api
    container_name: aprendo-en-casa-offline-contenido.api
    environment:
      "ASPNETCORE_ENVIRONMENT": Production
      "ASPNETCORE_CORS": "*"
      "Settings__CADENA_CONEXION": "mongodb://admin:admin@181.176.211.159:27017/contenidoDB?authSource=admin"
      "Settings__HORA_DESCARGA_INICIO": "02:00:00"
      "Settings__HORA_DESCARGA_INTERVALO": "00:30:00"
      "Settings__SERVIDOR_INTERVALO": 5
      "Settings__RUTA_ARCHIVOS": "c:/app/archivos"
      "Settings__RUTA_ACK": "c:/app/ack"
      "Settings__RUTA_TRAZABILIDAD": "c:/app/trazabilidad"
      "Settings__RUTA_CONTINUIDAD": "c:/app/continuidad"
      "Settings__PROGRAMACION_TODO": "00:00:10"
      #LOCAL TOKEN 
      "Token__TOKEN_SECRET": "THIS IS USED TO SIGN AND VERIFY JWT TOKENS REPLACE IT WITH YOUR OWN SECRET IT CAN BE ANY STRING"
      "Token__TOKEN_USER": "DOWNLOADOFFLINE_DEV"
      "Token__TOKEN_PASSWORD": "rYWXlDIqFSsjrpFEehaqYFkcofOsdFLdhsZIsViF3a6WxHZq0CFDdg=="
      "Token__TOKEN_CLIENT_ID": "download-offline_dev"
      "Token__TOKEN_EXPIRES_DAYS": 7
    networks:
    - ms
    ports:
    - 1903:80
    volumes:
    - /c/app/_certificates/:/https/
    - /c/app/ac/_log:/app/Log
    - /c/app/ac/archivos:/app/archivos
    - /c/app/ac/ack:/app/ack
    - /c/app/ac/trazabilidad:/app/trazabilidad
    - /c/app/ac/continuidad:/app/continuidad
    restart: on-failure
networks:
    ms:
      external: true
