version: "3.4"

services:
  doctrina:    
    image: "doctrina"
    build:
      context: .
      dockerfile: Dockerfile   
    #networks:
    #  - ms
    ports:
      - 80
    restart: on-failure
#networks:
#  ms:
#    driver: bridge
